/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RdpRouteImport } from './routes/rdp'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as MinecraftRouteImport } from './routes/minecraft'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CloudRouteImport } from './routes/cloud'
import { Route as BuyRouteImport } from './routes/buy'
import { Route as BrandingRouteImport } from './routes/branding'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'
import { Route as ServicesVpsRouteImport } from './routes/services.vps'
import { Route as ServicesRdpRouteImport } from './routes/services.rdp'
import { Route as ServicesMinecraftRouteImport } from './routes/services.minecraft'
import { Route as GamesSlugRouteImport } from './routes/games.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as CategorySlugPlanSlugRouteImport } from './routes/category.$slug.$planSlug'

const RdpRoute = RdpRouteImport.update({
  id: '/rdp',
  path: '/rdp',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const MinecraftRoute = MinecraftRouteImport.update({
  id: '/minecraft',
  path: '/minecraft',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyRoute = BuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandingRoute = BrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVpsRoute = ServicesVpsRouteImport.update({
  id: '/services/vps',
  path: '/services/vps',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRdpRoute = ServicesRdpRouteImport.update({
  id: '/services/rdp',
  path: '/services/rdp',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesMinecraftRoute = ServicesMinecraftRouteImport.update({
  id: '/services/minecraft',
  path: '/services/minecraft',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const CategorySlugPlanSlugRoute = CategorySlugPlanSlugRouteImport.update({
  id: '/$planSlug',
  path: '/$planSlug',
  getParentRoute: () => CategorySlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blogs': typeof BlogsRoute
  '/branding': typeof BrandingRoute
  '/buy': typeof BuyRoute
  '/cloud': typeof CloudRoute
  '/contact': typeof ContactRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/minecraft': typeof MinecraftRoute
  '/partner': typeof PartnerRoute
  '/payment': typeof PaymentRoute
  '/pricing': typeof PricingRoute
  '/rdp': typeof RdpRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/plans': typeof AdminPlansRoute
  '/category/$slug': typeof CategorySlugRouteWithChildren
  '/games/$slug': typeof GamesSlugRoute
  '/services/minecraft': typeof ServicesMinecraftRoute
  '/services/rdp': typeof ServicesRdpRoute
  '/services/vps': typeof ServicesVpsRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/category/$slug/$planSlug': typeof CategorySlugPlanSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRoute
  '/branding': typeof BrandingRoute
  '/buy': typeof BuyRoute
  '/cloud': typeof CloudRoute
  '/contact': typeof ContactRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/minecraft': typeof MinecraftRoute
  '/partner': typeof PartnerRoute
  '/payment': typeof PaymentRoute
  '/pricing': typeof PricingRoute
  '/rdp': typeof RdpRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/plans': typeof AdminPlansRoute
  '/category/$slug': typeof CategorySlugRouteWithChildren
  '/games/$slug': typeof GamesSlugRoute
  '/services/minecraft': typeof ServicesMinecraftRoute
  '/services/rdp': typeof ServicesRdpRoute
  '/services/vps': typeof ServicesVpsRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/services': typeof ServicesIndexRoute
  '/category/$slug/$planSlug': typeof CategorySlugPlanSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blogs': typeof BlogsRoute
  '/branding': typeof BrandingRoute
  '/buy': typeof BuyRoute
  '/cloud': typeof CloudRoute
  '/contact': typeof ContactRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/minecraft': typeof MinecraftRoute
  '/partner': typeof PartnerRoute
  '/payment': typeof PaymentRoute
  '/pricing': typeof PricingRoute
  '/rdp': typeof RdpRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/plans': typeof AdminPlansRoute
  '/category/$slug': typeof CategorySlugRouteWithChildren
  '/games/$slug': typeof GamesSlugRoute
  '/services/minecraft': typeof ServicesMinecraftRoute
  '/services/rdp': typeof ServicesRdpRoute
  '/services/vps': typeof ServicesVpsRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/category/$slug/$planSlug': typeof CategorySlugPlanSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blogs'
    | '/branding'
    | '/buy'
    | '/cloud'
    | '/contact'
    | '/legal'
    | '/login'
    | '/minecraft'
    | '/partner'
    | '/payment'
    | '/pricing'
    | '/rdp'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/plans'
    | '/category/$slug'
    | '/games/$slug'
    | '/services/minecraft'
    | '/services/rdp'
    | '/services/vps'
    | '/tools/$slug'
    | '/admin/'
    | '/services/'
    | '/category/$slug/$planSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blogs'
    | '/branding'
    | '/buy'
    | '/cloud'
    | '/contact'
    | '/legal'
    | '/login'
    | '/minecraft'
    | '/partner'
    | '/payment'
    | '/pricing'
    | '/rdp'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/plans'
    | '/category/$slug'
    | '/games/$slug'
    | '/services/minecraft'
    | '/services/rdp'
    | '/services/vps'
    | '/tools/$slug'
    | '/admin'
    | '/services'
    | '/category/$slug/$planSlug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blogs'
    | '/branding'
    | '/buy'
    | '/cloud'
    | '/contact'
    | '/legal'
    | '/login'
    | '/minecraft'
    | '/partner'
    | '/payment'
    | '/pricing'
    | '/rdp'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/plans'
    | '/category/$slug'
    | '/games/$slug'
    | '/services/minecraft'
    | '/services/rdp'
    | '/services/vps'
    | '/tools/$slug'
    | '/admin/'
    | '/services/'
    | '/category/$slug/$planSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogsRoute: typeof BlogsRoute
  BrandingRoute: typeof BrandingRoute
  BuyRoute: typeof BuyRoute
  CloudRoute: typeof CloudRoute
  ContactRoute: typeof ContactRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  MinecraftRoute: typeof MinecraftRoute
  PartnerRoute: typeof PartnerRoute
  PaymentRoute: typeof PaymentRoute
  PricingRoute: typeof PricingRoute
  RdpRoute: typeof RdpRoute
  CategorySlugRoute: typeof CategorySlugRouteWithChildren
  GamesSlugRoute: typeof GamesSlugRoute
  ServicesMinecraftRoute: typeof ServicesMinecraftRoute
  ServicesRdpRoute: typeof ServicesRdpRoute
  ServicesVpsRoute: typeof ServicesVpsRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rdp': {
      id: '/rdp'
      path: '/rdp'
      fullPath: '/rdp'
      preLoaderRoute: typeof RdpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minecraft': {
      id: '/minecraft'
      path: '/minecraft'
      fullPath: '/minecraft'
      preLoaderRoute: typeof MinecraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy': {
      id: '/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof BuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branding': {
      id: '/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof BrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/vps': {
      id: '/services/vps'
      path: '/services/vps'
      fullPath: '/services/vps'
      preLoaderRoute: typeof ServicesVpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/rdp': {
      id: '/services/rdp'
      path: '/services/rdp'
      fullPath: '/services/rdp'
      preLoaderRoute: typeof ServicesRdpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/minecraft': {
      id: '/services/minecraft'
      path: '/services/minecraft'
      fullPath: '/services/minecraft'
      preLoaderRoute: typeof ServicesMinecraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/category/$slug/$planSlug': {
      id: '/category/$slug/$planSlug'
      path: '/$planSlug'
      fullPath: '/category/$slug/$planSlug'
      preLoaderRoute: typeof CategorySlugPlanSlugRouteImport
      parentRoute: typeof CategorySlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CategorySlugRouteChildren {
  CategorySlugPlanSlugRoute: typeof CategorySlugPlanSlugRoute
}

const CategorySlugRouteChildren: CategorySlugRouteChildren = {
  CategorySlugPlanSlugRoute: CategorySlugPlanSlugRoute,
}

const CategorySlugRouteWithChildren = CategorySlugRoute._addFileChildren(
  CategorySlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogsRoute: BlogsRoute,
  BrandingRoute: BrandingRoute,
  BuyRoute: BuyRoute,
  CloudRoute: CloudRoute,
  ContactRoute: ContactRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  MinecraftRoute: MinecraftRoute,
  PartnerRoute: PartnerRoute,
  PaymentRoute: PaymentRoute,
  PricingRoute: PricingRoute,
  RdpRoute: RdpRoute,
  CategorySlugRoute: CategorySlugRouteWithChildren,
  GamesSlugRoute: GamesSlugRoute,
  ServicesMinecraftRoute: ServicesMinecraftRoute,
  ServicesRdpRoute: ServicesRdpRoute,
  ServicesVpsRoute: ServicesVpsRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
