/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RdpRouteImport } from './routes/rdp'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MinecraftRouteImport } from './routes/minecraft'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CloudRouteImport } from './routes/cloud'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as CategorySlugPlanSlugRouteImport } from './routes/category.$slug.$planSlug'

const RdpRoute = RdpRouteImport.update({
  id: '/rdp',
  path: '/rdp',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MinecraftRoute = MinecraftRouteImport.update({
  id: '/minecraft',
  path: '/minecraft',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugPlanSlugRoute = CategorySlugPlanSlugRouteImport.update({
  id: '/$planSlug',
  path: '/$planSlug',
  getParentRoute: () => CategorySlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cloud': typeof CloudRoute
  '/contact': typeof ContactRoute
  '/minecraft': typeof MinecraftRoute
  '/pricing': typeof PricingRoute
  '/rdp': typeof RdpRoute
  '/category/$slug': typeof CategorySlugRouteWithChildren
  '/category/$slug/$planSlug': typeof CategorySlugPlanSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cloud': typeof CloudRoute
  '/contact': typeof ContactRoute
  '/minecraft': typeof MinecraftRoute
  '/pricing': typeof PricingRoute
  '/rdp': typeof RdpRoute
  '/category/$slug': typeof CategorySlugRouteWithChildren
  '/category/$slug/$planSlug': typeof CategorySlugPlanSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cloud': typeof CloudRoute
  '/contact': typeof ContactRoute
  '/minecraft': typeof MinecraftRoute
  '/pricing': typeof PricingRoute
  '/rdp': typeof RdpRoute
  '/category/$slug': typeof CategorySlugRouteWithChildren
  '/category/$slug/$planSlug': typeof CategorySlugPlanSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cloud'
    | '/contact'
    | '/minecraft'
    | '/pricing'
    | '/rdp'
    | '/category/$slug'
    | '/category/$slug/$planSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cloud'
    | '/contact'
    | '/minecraft'
    | '/pricing'
    | '/rdp'
    | '/category/$slug'
    | '/category/$slug/$planSlug'
  id:
    | '__root__'
    | '/'
    | '/cloud'
    | '/contact'
    | '/minecraft'
    | '/pricing'
    | '/rdp'
    | '/category/$slug'
    | '/category/$slug/$planSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CloudRoute: typeof CloudRoute
  ContactRoute: typeof ContactRoute
  MinecraftRoute: typeof MinecraftRoute
  PricingRoute: typeof PricingRoute
  RdpRoute: typeof RdpRoute
  CategorySlugRoute: typeof CategorySlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rdp': {
      id: '/rdp'
      path: '/rdp'
      fullPath: '/rdp'
      preLoaderRoute: typeof RdpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minecraft': {
      id: '/minecraft'
      path: '/minecraft'
      fullPath: '/minecraft'
      preLoaderRoute: typeof MinecraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug/$planSlug': {
      id: '/category/$slug/$planSlug'
      path: '/$planSlug'
      fullPath: '/category/$slug/$planSlug'
      preLoaderRoute: typeof CategorySlugPlanSlugRouteImport
      parentRoute: typeof CategorySlugRoute
    }
  }
}

interface CategorySlugRouteChildren {
  CategorySlugPlanSlugRoute: typeof CategorySlugPlanSlugRoute
}

const CategorySlugRouteChildren: CategorySlugRouteChildren = {
  CategorySlugPlanSlugRoute: CategorySlugPlanSlugRoute,
}

const CategorySlugRouteWithChildren = CategorySlugRoute._addFileChildren(
  CategorySlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CloudRoute: CloudRoute,
  ContactRoute: ContactRoute,
  MinecraftRoute: MinecraftRoute,
  PricingRoute: PricingRoute,
  RdpRoute: RdpRoute,
  CategorySlugRoute: CategorySlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
